title: Cheng-Chun Hsu
position: MS student
affiliation: The University of Texas at Austin
affiliation_link: https://www.cs.utexas.edu/
email: chengchun (at) utexas.edu
keywords: chengchun hsu, hsu chengchun, chengchunhsu, hsuchengchun
google_scholar: https://scholar.google.com/citations?user=9rh0w2QAAAAJ
cv_link: data/Cheng-Chun_CV.pdf
github_link: https://github.com/chengchunhsu/
linkedin: https://www.linkedin.com/in/chengchun-hsu
twitter: 
avatar: ./assets/img/avatar.jpg
google_analytics: G-7GF0RHBSDK
favicon: ./assets/img/favicon.svg
favicon_dark: ./assets/img/favicon-dark.png
description: Cheng-Chun Hsu is a MS student at The University of Texas at Austin. His research lies at the intersection of robotics and computer vision.
canonical: https://chengchunhsu.github.io/
imprint: 
data_protection: 

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
